### ISSUE TITLE
Each Docker image must have the same name as its corresponding service

### ISSUE THREAD

**Issue by newmki** [newmki/inception#10]
Set docker image name with docker-compose.

**Comment by newmki** [comment]
### The way to change docker image in docker-compose.yml

- https://docs.docker.com/compose/compose-file/compose-file-v3/#image

```

```

**Comment by newmki** [comment]
### The way to set docker container name in docker-compose.yml

- https://docs.docker.com/compose/compose-file/compose-file-v3/#container_name

**Comment by newmki** [comment]
### How to maintain docker container in docker-compose

- https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir
- tty: docker run -t
- stdion_opn: docker run -i

```
version: "3.9"
services:
  service-name:
    build: ./Dockerfile
    tty: true
    stdin_open: true
```
