### ISSUE TITLE
Your containers musn’t be started with a command running an infinite loop. Thus, this also applies to any command used as entrypoint, or used in entrypoint scripts

### ISSUE THREAD

**Issue by newmki** [newmki/inception#22]

**Comment by newmki** [comment]
### How to maintain docker container in docker-compose

- https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir
- tty: docker run -t
- stdion_opn: docker run -i

```
version: "3.9"
services:
  service-name:
    build: ./Dockerfile
    tty: true
    stdin_open: true
```
